swagger: '2.0'
info:
  title: NWM Streams API
  description: Retrieves data from NWM Dataset based on given parameters
  version: 1.1.0
schemes:
  - https
produces:
  - application/json
paths:
  /:
    get:
      summary: Home for NWM API
      operationId: home
      x-google-backend:
        address: <APP_URL>
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /docs:
    get:
      summary: Documentation for NWM API
      operationId: docs
      x-google-backend:
        address: <APP_URL>
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response
          schema:
            type: string

  /openapi.json:
    get:
      summary: openapi.json for NWM API
      operationId: openapi-json
      x-google-backend:
        address: <APP_URL>
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /forecast:
    get:
      summary: Get forecast table contents
      operationId: return_forecast_records
      x-google-backend:
        address: <APP_URL>
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "forecast_type"
          in: "query"
          description: "Forecast table to retrive data from"
          required: true
          type: "string"
        - name: "comids"
          in: "query"
          description: "Unique identification for stream segment"
          required: true
          type: "number"
        - name: "hs_resource"
          in: "query"
          description: "Unique identification for HydroShare resource (with list of comids)"
          required: true
          type: "number"
        - name: "reference_time"
          in: "query"
          description: "Time in which forecast was generated"
          required: true
          type: "string"
        - name: "ensemble"
          in: "query"
          description: "One or more different ensembles"
          required: true
          type: "number"
        - name: "output_format"
          in: "query"
          description: "Output format. Options are csv and json"
          required: true
          type: "string"
      security:
        - api_key: []
      responses:
        "200":
          description: "Successful retrieval of data"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Response"
        "400":
          description: "Invalid parameters provided"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "500":
          description: "Internal Server Error"
          schema:
            type: string
  /analysis-assim:
    get:
      summary: Get analysis and assimilation table contents
      operationId: return_analysis-assim_records
      x-google-backend:
        address: <APP_URL>
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "start_time"
          in: "query"
          description: "Start time of analysis and assimilation data"
          required: true
          type: "string"
        - name: "end_time"
          in: "query"
          description: "End time of analysis and assimilation data"
          required: true
          type: "string"
        - name: "comids"
          in: "query"
          description: "Unique identification for stream segment"
          required: true
          type: "number"
        - name: "hs_resource"
          in: "query"
          description: "Unique identification for HydroShare resource (with list of comids)"
          required: true
          type: "number"
        - name: "run_offset"
          in: "query"
          description: "Look back time from model run"
          required: true
          type: "string"
        - name: "output_format"
          in: "query"
          description: "Output format. Options are csv and json"
          required: true
          type: "string"
      security:
        - api_key: []
      responses:
        "200":
          description: "Successful retrieval of data"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Response"
        "400":
          description: "Invalid parameters provided"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "500":
          description: "Internal Server Error"
          schema:
            type: string
  /geometry:
    get:
      summary: Get geometry table contents
      operationId: return_geometry
      x-google-backend:
        address: <APP_URL>
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "comids"
          in: "query"
          description: "Unique identification for stream segment"
          required: true
          type: "number"
        - name: "hs_resource"
          in: "query"
          description: "Unique identification for HydroShare resource (with list of comids)"
          required: true
          type: "number"
        - name: "lat"
          in: "query"
          description: "Latitude of point to select closest stream segment" 
          required: true
          type: "string"
        - name: "lon"
          in: "query"
          description: "Longitude of point to select closest stream segment" 
          required: true
          type: "string"
        - name: "output_format"
          in: "query"
          description: "Output format. Options are csv and json"
          required: true
          type: "string"
      security:
        - api_key: []
      responses:
        "200":
          description: "Successful retrieval of data"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Response"
        "400":
          description: "Invalid parameters provided"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "500":
          description: "Internal Server Error"
          schema:
            type: string

  /return-period:
    get:
      summary: Get flood return-period contents
      operationId: return_periods
      x-google-backend:
        address: <APP_URL>
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: "comids"
          in: "query"
          description: "Unique identification for stream segment"
          required: true
          type: "number"
        - name: "hydoshare_id"
          in: "query"
          description: "Unique identification for HydroShare resource (with list of comids)"
          required: true
          type: "number"
        - name: "return_periods"
          in: "query"
          description: "Extraction of a subset of available return periods" 
          required: false
          type: "string"
        - name: "output_format"
          in: "query"
          description: "Output format. Options are csv and json"
          required: true
          type: "string"
        - name: "order_by_comid"
          in: "query"
          description: "Ordering the records in the resulting data table" 
          required: false
          type: "boolean"
      security:
        - api_key: []
      responses:
        "200":
          description: "Successful retrieval of data"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Response"
        "400":
          description: "Invalid parameters provided"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "500":
          description: "Internal Server Error"
          schema:
            type: string

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  Response:
    type: "object"
    properties:
      featureID:
        type: "number"
