swagger: '2.0'
info:
  title: NWM Streams API
  description: Retrieves data from NWM Dataset based on given parameters
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /docs:
    get:
      summary: Documentation for NWM Streams API
      operationId: docs
      x-google-backend:
        address: <APP-URL>/docs
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /openapi.json:
    get:
      summary: openapi.json for NWM Streams API
      operationId: openapi-json
      x-google-backend:
        address: <APP-URL>/openapi.json
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /forecast:
    get:
      summary: Get forecast table contents
      operationId: return_forecast_records
      x-google-backend:
        address: <APP-URL>/forecast
      parameters:
        - name: "forecast_type"
          in: "query"
          description: "Forecast table to retrive data from"
          required: true
          type: "string"
        - name: "comids"
          in: "query"
          description: "Unique identification for stream segment"
          required: true
          type: "number"
        - name: "hs_resource"
          in: "query"
          description: "Unique identification for HydroShare resource (with list of comids)"
          required: true
          type: "number"
        - name: "reference_time"
          in: "query"
          description: "Time in which forecast was generated"
          required: true
          type: "string"
        - name: "ensemble"
          in: "query"
          description: "One or more different ensembles"
          required: true
          type: "number"
        - name: "output_format"
          in: "query"
          description: "Output format. Options are csv and json"
          required: true
          type: "string"
      security:
        - api_key: []
      responses:
        "200":
          description: "Successful retrieval of data"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Response"
        "400":
          description: "Invalid parameters provided"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "500":
          description: "Internal Server Error"
          schema:
            type: string
  /analysis-assim:
    get:
      summary: Get analysis and assimilation table contents
      operationId: return_analysis-assim_records
      x-google-backend:
        address: <APP-URL>/analysis-assim
      parameters:
        - name: "start_time"
          in: "query"
          description: "Start time of analysis and assimilation data"
          required: true
          type: "string"
        - name: "end_time"
          in: "query"
          description: "End time of analysis and assimilation data"
          required: true
          type: "string"
        - name: "comids"
          in: "query"
          description: "Unique identification for stream segment"
          required: true
          type: "number"
        - name: "hs_resource"
          in: "query"
          description: "Unique identification for HydroShare resource (with list of comids)"
          required: true
          type: "number"
        - name: "run_offset"
          in: "query"
          description: "Look back time from model run"
          required: true
          type: "string"
        - name: "output_format"
          in: "query"
          description: "Output format. Options are csv and json"
          required: true
          type: "string"
      security:
        - api_key: []
      responses:
        "200":
          description: "Successful retrieval of data"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Response"
        "400":
          description: "Invalid parameters provided"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "500":
          description: "Internal Server Error"
          schema:
            type: string
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  Response:
    type: "object"
    properties:
      featureID:
        type: "number"