swagger: '2.0'
info:
  title: NWM Streams API
  description: Retrieves data from NWM Streams Database based on given parameters
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /forecastrecords:
    get:
      summary: Get table contents
      operationId: return_forecastrecords
      x-google-backend:
        address: https://us-central1-nwm-ciroh.cloudfunctions.net/forecastrecords_1
      parameters:
        - name: "featureID"
          in: "query"
          description: "Unique identification for stream segment"
          required: true
          type: "number"
      security:
        - api_key: []
      responses:
        "200":
          description: "Successful retrieval of data"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Response"
        "400":
          description: "Invalid parameters provided"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "500":
          description: "Internal Server Error"
          schema:
            type: string
  /dailyaverages:
    get:
      summary: Get table contents
      operationId: return_dailyaverages
      x-google-backend:
        address: https://us-central1-nwm-ciroh.cloudfunctions.net/dailyaverages_1
      parameters:
        - name: "featureID"
          in: "query"
          description: "Unique identification for stream segment"
          required: true
          type: "number"
      security:
        - api_key: [ ]
      responses:
        "200":
          description: "Successful retrieval of data"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Response"
        "400":
          description: "Invalid parameters provided"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "500":
          description: "Internal Server Error"
          schema:
            type: string
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  Response:
    type: "object"
    properties:
      featureID:
        type: "number"

