steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/kmarkert-personal/nwm-api-repo/nwm-api-image', '.' ]
images: ['us-central1-docker.pkg.dev/kmarkert-personal/nwm-api-repo/nwm-api-image']